In [1]:
!pip install ordered-set

Defaulting to user installation because normal site-packages is not writeable


In [10]:
import pandas as pd
import numpy as np
from collections import Counter
from ordered_set import OrderedSet

In [11]:
d1 = "The cow jumped over the moon"
d2 = "O'Leary's cow kicked the lamp"
d3 = "The kicked lamp started a fire"
d4 = "The cow on fire"

In [16]:
def term_doc(*docs):
    dd = []
    for doc in docs:
        dd.append(list(map(lambda x: x.lower(), doc.split(' '))))
        
    counts = dict()
    for idx, doc in enumerate(dd):
        counts[idx] = Counter(doc)
        
    mat = pd.DataFrame(counts).replace(np.nan, 0)
    
    words = list(OrderedSet([word for doc in dd for word in doc]))
    
    return mat, words

In [17]:
mat, words = term_doc(d1, d2, d3, d4)
mat

0    1    2    3
the        2.0  1.0  1.0  1.0
cow        1.0  1.0  0.0  1.0
jumped     1.0  0.0  0.0  0.0
over       1.0  0.0  0.0  0.0
moon       1.0  0.0  0.0  0.0
o'leary's  0.0  1.0  0.0  0.0
kicked     0.0  1.0  1.0  0.0
lamp       0.0  1.0  1.0  0.0
started    0.0  0.0  1.0  0.0
a          0.0  0.0  1.0  0.0
fire       0.0  0.0  1.0  1.0
on         0.0  0.0  0.0  1.0

In [18]:
u, s, vt = np.linalg.svd (mat, full_matrices=False)

In [19]:
u,s,vt

(array([[-0.70701377, -0.19127925, -0.05030678, -0.11782658],
        [-0.40921666, -0.21126922,  0.07205224,  0.48568274],
        [-0.17254364, -0.29470143,  0.04273557, -0.27369126],
        [-0.17254364, -0.29470143,  0.04273557, -0.27369126],
        [-0.17254364, -0.29470143,  0.04273557, -0.27369126],
        [-0.12934189,  0.11257205,  0.4615164 ,  0.31939271],
        [-0.25459535,  0.42726345,  0.29642181, -0.01042535],
        [-0.25459535,  0.42726345,  0.29642181, -0.01042535],
        [-0.12525347,  0.3146914 , -0.16509458, -0.32981806],
        [-0.12525347,  0.3146914 , -0.16509458, -0.32981806],
        [-0.23258459,  0.28555156, -0.59729432,  0.11016323],
        [-0.10733113, -0.02913985, -0.43219973,  0.43998129]]),
 array([3.6833216 , 2.23942286, 1.52698177, 1.44445626]),
 array([[-0.63553373, -0.47640777, -0.4613488 , -0.39533505],
        [-0.65996111,  0.25209642,  0.70472713, -0.06525644],
        [ 0.06525644,  0.70472713, -0.25209642, -0.65996111],
        [-

In [21]:
# up, sp, vp = u[:, 9:2], np.diag(s[0:2]), vt[:, 0:2]

In [29]:
k = 2
up, sp, vp = u[:, :k], np.diag(s[:k]), vt[:k, :]

Ap = up @ sp @ vp
pd.DataFrame (Ap, index=words)
Ap

array([[ 1.93772865,  1.13265482,  0.89955219,  1.0574683 ],
       [ 1.27016664,  0.59880611,  0.36195893,  0.62675345],
       [ 0.83945179,  0.13639937, -0.17188977,  0.29431547],
       [ 0.83945179,  0.13639937, -0.17188977,  0.29431547],
       [ 0.83945179,  0.13639937, -0.17188977,  0.29431547],
       [ 0.13639937,  0.29051697,  0.39744934,  0.17188977],
       [-0.0354904 ,  0.6879663 ,  1.10693237,  0.30828914],
       [-0.0354904 ,  0.6879663 ,  1.10693237,  0.30828914],
       [-0.17188977,  0.39744934,  0.70948303,  0.13639937],
       [-0.17188977,  0.39744934,  0.70948303,  0.13639937],
       [ 0.1224257 ,  0.56933911,  0.8458824 ,  0.29694758],
       [ 0.29431547,  0.17188977,  0.13639937,  0.16054821]])

In [34]:
def sim(w1, w2):
    idx_w1 = words.index(w1)
    idx_w2 = words.index(w2)

    dot = np.dot(Ap[idx_w1], Ap[idx_w2])
    div = len(Ap[idx_w1]) * len(Ap[idx_w2])
    return dot / div

similarity1 = sim('the', 'cow')
print("Similarity between 'the' and 'cow':", similarity1)

similarity2 = sim('the', 'over')
print("Similarity between 'the' and 'over':", similarity2)

similarity3 = sim('over', 'lamp')
print("Similarity between 'over' and 'lamp':", similarity3)


Similarity between 'the' and 'cow': 0.25799073533786815
Similarity between 'on' and 'fire': 0.01855922350290649
Similarity between 'over' and 'lamp': -0.002218150305832753
