In [ ]:
import pandas as pd
import numpy as np
from collections import Counter
from ordered_set import OrderedSet
d1= "The cow jumped over the moon"
d2 = "O'Leary's cow kicked the lamp"
d3= "The kicked lamp started a fire"
d4 = "The cow on fire"

def term_doc(*docs):
  dd = []
  for doc in docs:
    dd.append(list(map(lambda x : x.lower(), doc.split(' '))))
  counts = dict()
  for idx, doc in enumerate(dd):
    counts[idx] = Counter (doc)

  mat = pd.DataFrame (counts).replace(np.nan, 0)
  words= list(OrderedSet([word for doc in dd for word in doc]))
  return mat, words


In [ ]:
mat, words = term_doc (d1, d2, d3, d4)
mat

0    1    2    3
the        2.0  1.0  1.0  1.0
cow        1.0  1.0  0.0  1.0
jumped     1.0  0.0  0.0  0.0
over       1.0  0.0  0.0  0.0
moon       1.0  0.0  0.0  0.0
o'leary's  0.0  1.0  0.0  0.0
kicked     0.0  1.0  1.0  0.0
lamp       0.0  1.0  1.0  0.0
started    0.0  0.0  1.0  0.0
a          0.0  0.0  1.0  0.0
fire       0.0  0.0  1.0  1.0
on         0.0  0.0  0.0  1.0

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.


In [ ]:
u, s, vt = np.linalg.svd (mat, full_matrices=False)

In [ ]:
u,s,vt

(array([[-0.70701377, -0.19127925, -0.05030678, -0.11782658],
        [-0.40921666, -0.21126922,  0.07205224,  0.48568274],
        [-0.17254364, -0.29470143,  0.04273557, -0.27369126],
        [-0.17254364, -0.29470143,  0.04273557, -0.27369126],
        [-0.17254364, -0.29470143,  0.04273557, -0.27369126],
        [-0.12934189,  0.11257205,  0.4615164 ,  0.31939271],
        [-0.25459535,  0.42726345,  0.29642181, -0.01042535],
        [-0.25459535,  0.42726345,  0.29642181, -0.01042535],
        [-0.12525347,  0.3146914 , -0.16509458, -0.32981806],
        [-0.12525347,  0.3146914 , -0.16509458, -0.32981806],
        [-0.23258459,  0.28555156, -0.59729432,  0.11016323],
        [-0.10733113, -0.02913985, -0.43219973,  0.43998129]]),
 array([3.6833216 , 2.23942286, 1.52698177, 1.44445626]),
 array([[-0.63553373, -0.47640777, -0.4613488 , -0.39533505],
        [-0.65996111,  0.25209642,  0.70472713, -0.06525644],
        [ 0.06525644,  0.70472713, -0.25209642, -0.65996111],
        [-

In [ ]:
up, sp, vp = u[:, 9:2], np.diag(s[0:2]), vt[:, 0:2]

Ap = up @ sp @ vp.T
Ap

ValueError: ignored